project:
  type: website
  output-dir: docs

website:
  title: "Christopher Hynes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: experience.qmd
        text: Experience
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/christopher-hynes
      - icon: linkedin
        href: https://www.linkedin.com/in/christopher-hynes

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; 2025, Christopher Hynes"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
